Brightness fixes
mate-desktop/mate-power-manager pull request #403
Opened 2024-10-07 15:49 UTC by ByteMaster1337

Fix a simple bug in KBD backlight toggle key handling and add some functionality to make KBD and LCD backlight control behave a bit more sane.
Fixes #187 as LCD brightness changes by function keys in battery mode are saved to config now.
It does not fix the problems with keyboard backlight described there, as I found this is a completely different issue. For example on my lenovo laptop, changing keyboard backlight by Fn+Space does not generate a scancode, thus GPM can't keep track of changes made to keyboard backlight. One might come up with some trickery to take such untracked changes in hardware into account, but I found a quick fix that adds a switch to completely disable KBD brightness control in dconf more useful for now.

2025-09-09 19:51 UTC, ByteMaster1337 commented
> I'm sorry that I didn't review this when I made #404, is there more to do that this PR does, or is it solved?

From a quick glance I guess your patches addressed most kbd_backlight-related things I had in this PR. This only leaves "backlight: Save brightness changes running on battery" and maybe parts of "add: switch kbd-backlight-enable" from this PR.
Unfortunately I'm currently quite busy with other things, but I'll try to clean this up.

2025-09-09 21:06 UTC, ByteMaster1337 commented
On a slightly deeper look:
My ["backlight: Save brightness changes running on battery"](https://github.com/mate-desktop/mate-power-manager/pull/403/commits/2dcda91ff9ea8f07ab43674a17933a5c52496a8f) indeed doesn't conflict and is ready to merge, if you agree with this functionality change.

My https://github.com/mate-desktop/mate-power-manager/pull/403/commits/e363c9f0099f0b6461dbf312ae0a639f23cc0191:
The conflict is only caused by this refactor commit: "refactor: gpm-kbd-backlight: Move dimming logic to a helper function". The local variable and if-block still go to the start of gpm_kbd_backlight_evaluate_power_source_and_set. So if you agree to this additional functionality, this should be easy to merge.

The rest isn't so easy...
@cwendling 
My https://github.com/mate-desktop/mate-power-manager/pull/403/commits/e25e6f4eb3a8ccb69dc45751841005f6b7ca248c vs your "gpm-kbd-backlight: Fix toggling backlight back on":
I suggest favoring my solution for the following reason:
The _ONLY_ case where backlight master should be stored into this static "buffer" variable is when toggling off the backlight, for having the previous value ready for the toggle on case. There is no other case where setting this variable to master makes any sense whatsoever - including initialization.
Behavior in your patch:
*Function gets called for the first time; saved_brightness gets set to master
  *toggle-on-case: backlight is set to master value, which is 0 in this case. --> initialization of this variable in toggle-on-case results in behavior previous to this patch. Doesn't matter here though as brightness master must have been set to 0 here before by other means anyways.
  *any other case: initialization has no effect as save_brightness isn't used or will get written to (toggle-off-case).
Conclusion: The initialization to master makes no sense, logically.

Behavior in my patch:
*Function gets called for the first time: save_brightness is initialized to 0 (static variables get initialized to 0 by default).
  *toggle-on-case: As explained above, if this happens, master brightness must have been set to 0 beforehand by other means, so restoring the 0 initialized by default, is correct here.
  *any other case: save_brightness isn't used or will get written to (toggle-off-case).
Conclusion: Initializing save_brightness to 0 is, in my opinion, the logically correct behavior here.

My "[fix: kbd-backlight: Always set brightness](https://github.com/mate-desktop/mate-power-manager/commit/8c81c569166a3ff3988dadbfe16694942fe145eb)" probably conflicts in basic function logic, or basic kbd-backlight function behavior. Still need to look closer into this and what your patches do.

2025-09-10 21:14 UTC, ByteMaster1337 commented
Reworked my patches and dropped the "fix: kbd-backlight: Always set brightness" patch as it did basically the same as [gpm-kbd-backlight: Rationalize handling of battery-reduce setting](https://github.com/mate-desktop/mate-power-manager/pull/404/commits/cf76826417831e0ee6fcd90ad2da76d9f2c37f30)

So if you're ok with the changes I propose, I think we're good to go.

BTW:
If possible, please don't squash on merge like with [Keyboard backlight handling improvements](https://github.com/mate-desktop/mate-power-manager/commit/a0aeec575ba18d1101d783d640999df117daf28f). Most of the time this just creates barely readable commit blobs.
I learned the gitHub philosophy is to create own merge requests for every little change you do. So for example this here actually should have been 3 separate merge requests. If that's also your project philosophy, I apologize for this mess.

2025-09-11 12:06 UTC, vkareh requested changes
Code LGTM, with minor changes requested.

2025-09-26 15:47 UTC, vkareh approved these changes

2025-09-26 15:50 UTC, merged

2025-09-26 15:55 UTC, vkareh commented
> If possible, please don't squash on merge like with [Keyboard backlight handling improvements](https://github.com/mate-desktop/mate-power-manager/commit/a0aeec575ba18d1101d783d640999df117daf28f). Most of the time this just creates barely readable commit blobs.

You added commits with `--fixup`, which I expected GitHub to autosquash, but I wonder if GitHub doesn't honor that when using the "Rebase and Merge" option? Sigh...